# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - script: |
      echo "Listing files in the repository:"
      ls -alh  # Check the file structure in the repository
    displayName: 'List Files in Repository'

  - script: |
      npm install
      npm run build
    displayName: 'Install Dependencies and Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.SourcesDirectory)/build'  # Adjust if needed
      artifactName: 'frontend'
